ofctrl: Placate GCC.
Some GCC versions don't like ".x.y =", complaining about an uninitialized
field.

Without this patch we get travis failures, e.g.
https://travis-ci.org/openvswitch/ovs/jobs/410404752:

    ovn/controller/ofctrl.c: In function ‘ofctrl_put’:
    ovn/controller/ofctrl.c:1086:9: error: missing initializer for field ‘flags’ of ‘struct ofputil_meter_config’ [-Werror=missing-field-initializers]
             };
             ^
    In file included from ovn/controller/ofctrl.c:35:0:
    ./include/openvswitch/ofp-meter.h:53:14: note: ‘flags’ declared here
         uint16_t flags;
                  ^

With it, it passes.

Fixes: 185b13f228ac ("ovn: Add Meter and Meter_Band tables to the NB and SB databases.")
Signed-off-by: Ben Pfaff <blp@ovn.org>
Acked-by: Justin Pettit <jpettit@ovn.org>
(cherry picked from commit 1a7f7969d397b21943977aa02da927a299fc8e76)
Signed-off-by: Simon Horman <simon.horman@netronome.com>